# Generated by Django 4.0.5 on 2022-06-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('historia', models.CharField(max_length=250, verbose_name='Historia')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('tecnica', models.CharField(max_length=75, verbose_name='Tecnica usada')),
                ('nombreAutor', models.CharField(max_length=75, verbose_name='Nombre autor')),
            ],
        ),
    ]
