# Generated by Django 4.0.5 on 2022-06-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('idAutor', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del autor')),
                ('nombreAutor', models.CharField(max_length=60, verbose_name='Nombre del autor')),
                ('apellidoAutor', models.CharField(max_length=60, verbose_name='Apellido del autor')),
                ('numObras', models.IntegerField(verbose_name='Numero de obras')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('idObra', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de obra')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('historia', models.CharField(max_length=250, verbose_name='Historia')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('tecnica', models.CharField(max_length=75, verbose_name='Tecnica usada')),
                ('idAutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.autor')),
            ],
        ),
    ]
