# Generated by Django 4.0.5 on 2022-06-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='numObras',
        ),
        migrations.AlterField(
            model_name='obra',
            name='descripcion',
            field=models.CharField(max_length=250, verbose_name='Descripcion'),
        ),
    ]
