# Generated by Django 4.0.5 on 2022-06-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_obra_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='imagen',
            field=models.ImageField(null=True, upload_to='obrasimg', verbose_name='Imagen'),
        ),
    ]
